lista = list(["domingo","lunes","martes","miercoles","jueves"])
print(lista)
method = len(lista)
print(method)
lista.append("viernes")
print(lista)
lista.insert(6,"sabado")
print(lista)
lista.extend(["domingo","osvaldo"])
print(lista)
lista.pop(8)
print(lista)
lista.pop(-1)
print(lista)
lista.remove("lunes")
print(lista)

lista1 = list([2,5,3,8,5,9,4,1,False,True,True])
print(lista1)
lista1.reverse()
print(lista1)
lista1.sort()
print(lista1)
lista1.sort(reverse=True)
print(lista1)
lista1.clear()
print(lista1)