cadena = "tExto"
metodo = cadena.upper()
print(metodo)
metodo = cadena.lower()
print(metodo)
metodo = cadena.capitalize()
print(metodo)
metodo = cadena.find("T")
print(metodo)
metodo = cadena.index("t")
print(metodo)
metodo = cadena.isnumeric()
print(metodo)
metodo = cadena.isalpha()
print(metodo)
metodo = cadena.count("t")
print(metodo)
metodo = len(cadena)
print(metodo)
metodo = cadena.endswith("o")
print(metodo)
metodo = cadena.startswith("T")
print(metodo)
metodo = cadena.replace("E","e")
print(metodo)
print(metodo.capitalize())
metodo = cadena.split("x")
print(metodo)
print(type(metodo))